source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
inhibit_all_warnings!
platform :ios, '10.0'

target 'CYShare_Example' do
  pod 'CYShare', :path => '../'

  target 'CYShare_Tests' do
    inherit! :search_paths

    
  end
end
